-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: db
-- Tiempo de generación: 07-04-2024 a las 00:24:21
-- Versión del servidor: 8.2.0
-- Versión de PHP: 8.2.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `recipes_db`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `recipe`
--

CREATE TABLE `recipe` (
  `id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `ingredients` text NOT NULL,
  `instructions` text NOT NULL,
  `preparationTime` int DEFAULT NULL,
  `servings` int DEFAULT NULL,
  `photoUrl` varchar(255) DEFAULT NULL,
  `protein_per_Serving` float DEFAULT NULL,
  `magnesium_per_Serving` float DEFAULT NULL,
  `iron_per_Serving` float DEFAULT NULL,
  `calcium_per_Serving` float DEFAULT NULL,
  `vitaminC_per_Serving` float DEFAULT NULL,
  `fiber_per_Serving` float DEFAULT NULL,
  `calories_per_Serving` float DEFAULT NULL,
  `totalFats_per_Serving` float DEFAULT NULL,
  `sugars_per_Serving` float DEFAULT NULL,
  `sodium_per_Serving` float DEFAULT NULL,
  `isVegetarian` tinyint(1) DEFAULT NULL,
  `isVegan` tinyint(1) DEFAULT NULL,
  `suitableForDiabetics` tinyint(1) DEFAULT NULL,
  `lowInSodium` tinyint(1) DEFAULT NULL,
  `glutenFree` tinyint(1) DEFAULT NULL,
  `isBreakfast` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Volcado de datos para la tabla `recipe`
--

INSERT INTO `recipe` (`id`, `name`, `description`, `ingredients`, `instructions`, `preparationTime`, `servings`, `photoUrl`, `protein_per_Serving`, `magnesium_per_Serving`, `iron_per_Serving`, `calcium_per_Serving`, `vitaminC_per_Serving`, `fiber_per_Serving`, `calories_per_Serving`, `totalFats_per_Serving`, `sugars_per_Serving`, `sodium_per_Serving`, `isVegetarian`, `isVegan`, `suitableForDiabetics`, `lowInSodium`, `glutenFree`, `isBreakfast`) VALUES
(3, 'Quinoa Veggie Bowl', 'A nutritious and vibrant veggie bowl with quinoa and assorted vegetables.', 'Quinoa, broccoli, carrots, red bell pepper, avocado, lemon juice, olive oil.', 'Cook quinoa as directed. Steam broccoli and carrots until tender. Slice bell pepper and avocado. Mix all ingredients and dress with lemon juice and olive oil.', 25, 4, NULL, 8, 30, 2, 50, 60, 7, 350, 9, 3, 10, 1, 1, 1, 1, 1, 0),
(4, 'Banana Oat Pancakes', 'Fluffy and healthy banana oat pancakes, perfect for breakfast.', 'Bananas, oats, eggs, baking powder, cinnamon.', 'Blend all ingredients until smooth. Pour batter onto a hot non-stick skillet and cook until bubbles form. Flip and cook until golden.', 15, 3, NULL, 6, 20, 1.5, 20, 0, 4, 200, 5, 7, 150, 0, 0, 1, 0, 1, 1),
(5, 'Lentil Soup', 'A hearty and delicious lentil soup, rich in protein and fiber.', 'Lentils, carrots, onions, celery, tomatoes, vegetable broth, spices.', 'Saute onions, carrots, and celery. Add lentils, tomatoes, broth, and spices. Simmer until lentils are tender.', 45, 6, NULL, 18, 35, 4, 60, 20, 8, 220, 1, 6, 30, 1, 1, 1, 1, 1, 0),
(6, 'Avocado Toast', 'Simple yet satisfying avocado toast with a protein boost.', 'Whole grain bread, avocado, egg, red pepper flakes, salt.', 'Toast bread. Mash avocado and spread on toast. Top with a fried or poached egg and sprinkle with red pepper flakes and salt.', 10, 1, NULL, 10, 15, 2, 30, 15, 5, 300, 20, 2, 200, 1, 0, 1, 0, 1, 1),
(7, 'Mango Smoothie Bowl', 'A tropical mango smoothie bowl topped with fresh fruits and nuts.', 'Mango, banana, coconut milk, honey, mixed nuts, berries.', 'Blend mango, banana, and coconut milk until smooth. Pour into a bowl and top with nuts and berries.', 10, 2, NULL, 5, 25, 1, 20, 60, 6, 250, 8, 15, 5, 0, 0, 1, 0, 0, 1),
(8, 'Spicy Chickpea Curry', 'A flavorful and spicy chickpea curry, perfect with rice or bread.', 'Chickpeas, tomatoes, coconut milk, onions, spices.', 'Saute onions and spices. Add chickpeas, tomatoes, and coconut milk. Simmer until thickened.', 30, 4, NULL, 9, 40, 3, 50, 10, 8, 360, 10, 9, 700, 1, 1, 1, 0, 1, 0),
(9, 'Chicken Caesar Salad', 'A classic Caesar salad with juicy grilled chicken.', 'Romaine lettuce, chicken breast, croutons, parmesan cheese, Caesar dressing.', 'Grill chicken. Toss lettuce, chicken, croutons, and cheese with dressing.', 20, 4, NULL, 25, 15, 2, 70, 5, 3, 450, 27, 4, 550, 0, 0, 0, 0, 0, 0),
(10, 'Vegetable Stir-Fry', 'A quick and easy vegetable stir-fry, full of flavor.', 'Mixed vegetables, soy sauce, garlic, ginger, olive oil.', 'Saute garlic and ginger. Add vegetables and soy sauce. Stir-fry until vegetables are tender.', 15, 4, NULL, 5, 20, 1, 25, 15, 4, 180, 7, 8, 500, 1, 0, 1, 0, 1, 0),
(11, 'Greek Salad', 'A refreshing Greek salad with tomatoes, cucumber, olives, and feta.', 'Tomatoes, cucumber, red onion, olives, feta cheese, olive oil, vinegar.', 'Combine all ingredients and dress with olive oil and vinegar.', 10, 4, NULL, 6, 10, 1, 150, 20, 3, 220, 15, 5, 580, 0, 0, 1, 0, 1, 0),
(12, 'Zucchini Noodles with Pesto', 'A light and healthy zucchini noodle dish with homemade pesto.', 'Zucchini, basil, garlic, pine nuts, parmesan cheese, olive oil.', 'Spiralize zucchini. Blend basil, garlic, nuts, cheese, and oil for pesto. Combine.', 20, 2, NULL, 7, 25, 2, 130, 15, 3, 290, 20, 4, 210, 1, 0, 1, 0, 1, 0),
(13, 'Mexican Quinoa Salad', 'A zesty Mexican-inspired quinoa salad with black beans and corn.', 'Quinoa, black beans, corn, tomatoes, avocado, lime juice, spices.', 'Cook quinoa. Mix with beans, corn, tomatoes, and avocado. Dress with lime juice and spices.', 30, 4, NULL, 8, 30, 3, 45, 25, 7, 320, 5, 3, 15, 1, 1, 1, 1, 1, 0),
(14, 'Blueberry Muffins', 'Delightful blueberry muffins that are perfect for a quick breakfast.', 'Blueberries, flour, sugar, eggs, milk, baking powder.', 'Mix dry ingredients. Add eggs and milk. Fold in blueberries. Bake until golden.', 25, 12, NULL, 3, 10, 0.5, 20, 0, 2, 180, 7, 16, 220, 0, 0, 1, 0, 1, 1),
(15, 'Carrot Ginger Soup', 'A smooth and comforting carrot ginger soup, ideal for cold evenings.', 'Carrots, ginger, onions, vegetable broth, coconut milk.', 'Saute onions and ginger. Add carrots and broth. Blend until smooth. Stir in coconut milk.', 40, 4, NULL, 2, 15, 0.7, 40, 12, 5, 160, 4, 9, 120, 1, 1, 1, 1, 1, 0),
(16, 'BBQ Chicken Pizza', 'A delicious BBQ chicken pizza with a homemade crust.', 'Pizza dough, chicken breast, BBQ sauce, red onions, cheese.', 'Prepare pizza dough. Top with BBQ sauce, chicken, onions, and cheese. Bake.', 90, 8, NULL, 20, 5, 2, 220, 0, 2, 400, 10, 7, 900, 0, 0, 0, 0, 0, 0),
(17, 'Spinach and Feta Omelette', 'A fluffy omelette filled with spinach and feta cheese.', 'Eggs, spinach, feta cheese, olive oil, salt, pepper.', 'Whisk eggs. Cook spinach. Add eggs to skillet, then spinach and feta. Fold and serve.', 15, 2, NULL, 12, 20, 2, 200, 0, 2, 250, 18, 3, 400, 0, 0, 1, 0, 0, 1),
(18, 'Tofu Stir-Fry', 'A flavorful tofu stir-fry with vegetables and a soy sauce glaze.', 'Tofu, mixed vegetables, soy sauce, garlic, ginger.', 'Press tofu. Saute garlic, ginger, and tofu. Add vegetables and soy sauce. Stir-fry.', 20, 4, NULL, 14, 30, 3, 60, 10, 6, 350, 12, 7, 530, 1, 1, 1, 0, 1, 0),
(19, 'Salmon with Asparagus', 'A simple and elegant salmon dish with roasted asparagus.', 'Salmon fillets, asparagus, lemon, olive oil, salt, pepper.', 'Season salmon and asparagus. Roast until salmon is flaky and asparagus is tender.', 30, 4, NULL, 23, 30, 1.5, 60, 15, 3, 300, 15, 0, 70, 0, 0, 1, 1, 0, 0),
(20, 'Pumpkin Spice Latte', 'A warm and cozy homemade pumpkin spice latte.', 'Espresso, pumpkin puree, milk, sugar, pumpkin spice.', 'Mix espresso, pumpkin puree, and milk. Heat and add sugar and spice. Top with whipped cream.', 10, 2, NULL, 3, 10, 0.3, 100, 0, 0, 150, 3, 12, 95, 0, 0, 1, 0, 0, 1),
(21, 'Roasted Veggie Pizza', 'A hearty pizza topped with roasted vegetables.', 'Pizza dough, tomato sauce, bell peppers, onions, mushrooms, cheese.', 'Prepare dough. Spread sauce. Top with roasted vegetables and cheese. Bake.', 90, 6, NULL, 15, 20, 2, 180, 5, 4, 280, 9, 6, 800, 0, 0, 1, 0, 0, 0),
(22, 'Beef and Broccoli Stir-Fry', 'A classic beef and broccoli stir-fry with a savory sauce.', 'Beef slices, broccoli, soy sauce, garlic, ginger, sugar.', 'Marinate beef. Saute garlic and ginger. Add beef and broccoli. Stir in soy sauce and sugar.', 20, 4, NULL, 25, 35, 3.5, 60, 0, 4, 320, 14, 6, 600, 0, 0, 1, 0, 1, 0),
(23, 'Sweet Potato Hash', 'A sweet and savory breakfast hash with sweet potatoes, onions, and peppers.', 'Sweet potatoes, onion, bell pepper, eggs, olive oil, salt, paprika.', 'Dice and saut sweet potatoes, onions, and peppers. Crack eggs over the hash and cover until eggs are set.', 30, 4, NULL, 12, 40, 2.5, 55, 19, 6, 310, 11, 7, 170, 0, 0, 1, 1, 0, 1),
(24, 'Mushroom Risotto', 'Creamy mushroom risotto, rich in flavor and comforting.', 'Arborio rice, mushrooms, vegetable broth, parmesan cheese, onions, garlic, white wine.', 'Saut mushrooms, onions, and garlic. Add rice and broth gradually, stirring until creamy. Finish with parmesan.', 45, 4, NULL, 8, 25, 1.7, 20, 0, 3, 350, 14, 2, 125, 1, 0, 1, 0, 1, 0),
(25, 'Turmeric Golden Milk', 'A warming and healing turmeric golden milk, perfect for evenings.', 'Milk (or almond milk), turmeric, honey, cinnamon, ginger.', 'Warm milk with turmeric, honey, cinnamon, and ginger. Stir until well mixed and heated through.', 10, 2, NULL, 8, 22, 0.8, 300, 0, 0, 90, 5, 12, 60, 1, 1, 1, 0, 0, 1),
(26, 'Caprese Salad', 'A simple Italian salad, made of mozzarella, tomatoes, basil, seasoned with olive oil and balsamic glaze.', 'Fresh mozzarella, tomatoes, fresh basil, olive oil, balsamic glaze.', 'Layer sliced tomatoes and mozzarella, add basil leaves. Drizzle with olive oil and balsamic glaze.', 10, 2, NULL, 18, 15, 1, 220, 10, 2, 290, 20, 5, 210, 1, 0, 1, 0, 1, 0),
(27, 'Thai Green Curry', 'Spicy and aromatic Thai green curry with chicken and vegetables.', 'Chicken breast, coconut milk, green curry paste, bamboo shoots, bell pepper, basil.', 'Saut chicken, add vegetables and curry paste. Pour in coconut milk and simmer. Serve with basil.', 35, 4, NULL, 25, 50, 3.2, 40, 15, 3, 450, 27, 6, 760, 0, 0, 1, 0, 0, 0),
(28, 'Chia Seed Pudding', 'A healthy and easy-to-make chia seed pudding with berries.', 'Chia seeds, almond milk, honey, vanilla extract, mixed berries.', 'Mix chia seeds, almond milk, honey, and vanilla. Refrigerate overnight. Top with berries before serving.', 480, 2, NULL, 4, 95, 1.9, 200, 0, 10, 180, 8, 12, 30, 1, 1, 1, 1, 0, 1),
(29, 'Falafel Wrap', 'A Middle Eastern falafel wrap filled with crispy falafel, vegetables, and tahini sauce.', 'Falafel, whole wheat wraps, lettuce, tomato, cucumber, tahini.', 'Prepare falafel according to recipe. Fill wraps with falafel, veggies, and tahini sauce.', 20, 4, NULL, 13, 60, 4.1, 100, 5, 9, 320, 14, 3, 540, 1, 1, 1, 0, 0, 0),
(30, 'Kale and Quinoa Salad', 'A nutrient-packed salad with kale, quinoa, cranberries, and almonds.', 'Kale, quinoa, dried cranberries, almonds, lemon vinaigrette.', 'Toss kale, cooked quinoa, cranberries, and almonds with lemon vinaigrette.', 25, 4, NULL, 7, 30, 2.3, 115, 50, 5, 210, 9, 11, 70, 1, 1, 1, 1, 1, 0),
(31, 'Tomato Basil Soup', 'A classic tomato basil soup, both creamy and rich.', 'Tomatoes, vegetable broth, onions, garlic, basil, cream.', 'Saut onions and garlic. Add tomatoes and broth, simmer. Blend until smooth, stir in cream and basil.', 40, 6, NULL, 3, 18, 1.4, 70, 25, 2, 160, 10, 8, 410, 1, 0, 1, 0, 0, 0),
(32, 'Szechuan Tofu', 'Spicy and flavorful Szechuan tofu with stir-fried vegetables.', 'Tofu, bell peppers, Szechuan sauce, garlic, ginger, peanuts.', 'Press tofu, then saut with vegetables and Szechuan sauce. Serve with peanuts.', 20, 4, NULL, 15, 55, 3.7, 80, 6, 7, 300, 16, 6, 720, 1, 1, 1, 0, 1, 0),
(33, 'Apple Cinnamon Oatmeal', 'A warm and comforting apple cinnamon oatmeal, perfect for chilly mornings.', 'Oats, apple, cinnamon, almond milk, maple syrup.', 'Cook oats and almond milk. Add diced apple and cinnamon. Sweeten with maple syrup.', 15, 2, NULL, 5, 40, 2, 50, 0, 4, 220, 3, 14, 80, 1, 1, 1, 1, 0, 1),
(34, 'Ratatouille', 'A traditional French stewed vegetable dish, flavored with herbs.', 'Eggplant, zucchini, bell pepper, tomato, onion, garlic, herbs.', 'Saut vegetables separately, then layer in a dish and bake with herbs.', 60, 6, NULL, 4, 30, 1.5, 40, 20, 6, 140, 7, 8, 75, 1, 1, 1, 1, 0, 0),
(35, 'Paella', 'A vibrant Spanish rice dish with seafood, chicken, and vegetables.', 'Rice, chicken, shrimp, mussels, peas, bell peppers, saffron.', 'Cook chicken and seafood with vegetables and rice. Season with saffron and simmer.', 60, 6, NULL, 22, 45, 2.8, 60, 10, 3, 380, 12, 4, 780, 0, 0, 0, 0, 0, 0),
(36, 'Butternut Squash Soup', 'A creamy and comforting butternut squash soup with a hint of nutmeg.', 'Butternut squash, vegetable broth, onion, garlic, cream, nutmeg.', 'Roast squash. Saut onion and garlic. Blend all ingredients until smooth. Stir in cream.', 45, 4, NULL, 2, 25, 1.2, 80, 12, 3, 150, 5, 6, 220, 1, 0, 1, 0, 0, 0),
(37, 'Grilled Salmon with Mango Salsa', 'Freshly grilled salmon topped with a sweet and spicy mango salsa.', 'Salmon, mango, red onion, jalapeo, cilantro, lime.', 'Grill salmon. Mix mango, onion, jalapeo, and cilantro for the salsa. Serve on salmon.', 20, 4, NULL, 24, 35, 0.9, 55, 20, 3, 310, 14, 5, 85, 0, 0, 1, 1, 0, 0),
(38, 'Vegetable Lasagna', 'A hearty vegetable lasagna with layers of ricotta, mozzarella, and vegetables.', 'Lasagna noodles, ricotta cheese, mozzarella cheese, spinach, zucchini, marinara sauce.', 'Layer cooked noodles with cheeses, spinach, zucchini, and sauce. Bake until bubbly.', 60, 8, NULL, 15, 40, 2.2, 200, 10, 4, 350, 16, 6, 560, 1, 0, 1, 0, 0, 0),
(39, 'Shakshuka', 'A North African dish of poached eggs in a sauce of tomatoes, chili peppers, and onions, often spiced with cumin.', 'Eggs, tomatoes, onion, bell pepper, garlic, cumin, chili powder.', 'Saut vegetables and spices. Crack eggs into the sauce. Cover and cook until eggs are set.', 30, 4, NULL, 12, 35, 2.4, 55, 15, 5, 180, 9, 7, 400, 1, 0, 1, 0, 0, 1),
(40, 'Pumpkin Pie', 'A classic pumpkin pie, spiced with cinnamon, ginger, and nutmeg, perfect for the fall season.', 'Pumpkin puree, eggs, cream, sugar, cinnamon, ginger, nutmeg, pie crust.', 'Mix pumpkin, eggs, cream, and spices. Pour into crust. Bake until set.', 90, 8, NULL, 5, 20, 1.6, 70, 2, 2, 280, 14, 22, 210, 0, 0, 1, 0, 0, 0),
(41, 'Cauliflower Tacos', 'Tacos filled with spiced roasted cauliflower, topped with avocado and cilantro-lime crema.', 'Cauliflower, taco seasoning, corn tortillas, avocado, lime, cilantro.', 'Roast cauliflower with seasoning. Serve in tortillas with avocado and cilantro-lime crema.', 30, 4, NULL, 3, 25, 1.8, 45, 15, 5, 240, 12, 3, 300, 1, 1, 1, 0, 1, 0),
(42, 'Chocolate Avocado Mousse', 'A rich and creamy chocolate mousse made with avocados, perfect for a healthy dessert.', 'Avocados, cocoa powder, honey, vanilla extract, salt.', 'Blend avocados, cocoa, honey, vanilla, and salt until smooth. Chill before serving.', 15, 4, NULL, 4, 30, 1.5, 20, 0, 7, 220, 15, 12, 10, 1, 1, 1, 1, 0, 0),
(43, 'Eggplant Parmesan', 'Crispy baked eggplant slices layered with marinara and mozzarella.', 'Eggplant, breadcrumbs, eggs, marinara sauce, mozzarella cheese, basil.', 'Bread and bake eggplant slices, layer with marinara and mozzarella, bake until golden.', 50, 6, NULL, 18, 29, 2.2, 210, 15, 7, 320, 16, 8, 670, 1, 0, 1, 0, 0, 0),
(44, 'Veggie Breakfast Burrito', 'A filling breakfast burrito with eggs, black beans, avocado, and cheese.', 'Eggs, black beans, avocado, cheddar cheese, whole wheat tortillas, salsa.', 'Scramble eggs, mix with beans, avocado, and cheese, wrap in tortillas, serve with salsa.', 15, 4, NULL, 14, 40, 3.5, 190, 20, 6, 350, 15, 3, 690, 0, 0, 1, 1, 0, 1),
(45, 'Coconut Curry Lentils', 'Creamy coconut curry lentils, served over fragrant jasmine rice.', 'Lentils, coconut milk, curry powder, tomatoes, onion, garlic, jasmine rice.', 'Cook lentils with coconut milk, curry powder, tomatoes, and aromatics, serve over rice.', 45, 6, NULL, 19, 70, 4, 55, 25, 9, 410, 13, 7, 430, 1, 1, 1, 0, 0, 0),
(46, 'Baked Cod with Lemon', 'Simple baked cod seasoned with lemon, garlic, and herbs.', 'Cod fillets, lemon, garlic, parsley, olive oil, salt, pepper.', 'Bake cod with lemon, garlic, parsley, season, until flaky.', 20, 4, NULL, 22, 50, 1.2, 60, 0, 0, 190, 5, 1, 85, 0, 0, 1, 1, 0, 0),
(47, 'Stuffed Bell Peppers', 'Bell peppers stuffed with a savory mix of beef, rice, and tomato sauce.', 'Bell peppers, ground beef, cooked rice, tomato sauce, onions, cheese.', 'Stuff peppers with beef, rice, sauce mixture, top with cheese, bake until tender.', 60, 6, NULL, 21, 45, 3.8, 220, 60, 5, 420, 17, 6, 750, 0, 0, 0, 0, 0, 0),
(48, 'Pear and Gorgonzola Salad', 'A fresh salad with pears, gorgonzola, walnuts, and a balsamic vinaigrette.', 'Pears, gorgonzola cheese, walnuts, mixed greens, balsamic vinaigrette.', 'Combine pears, cheese, walnuts, greens, dress with vinaigrette.', 15, 4, NULL, 7, 20, 1.5, 150, 10, 4, 250, 19, 5, 520, 1, 0, 1, 0, 0, 0),
(49, 'Moroccan Chickpea Stew', 'A flavorful stew with chickpeas, sweet potatoes, and Moroccan spices.', 'Chickpeas, sweet potatoes, tomatoes, Moroccan spices, onion, garlic, vegetable broth.', 'Cook all ingredients until sweet potatoes are tender, spices melded.', 40, 6, NULL, 9, 60, 2.4, 55, 30, 8, 290, 6, 11, 460, 1, 1, 1, 0, 0, 0),
(50, 'Pesto Pasta Salad', 'A refreshing pasta salad tossed with homemade pesto, cherry tomatoes, and mozzarella.', 'Pasta, basil pesto, cherry tomatoes, mozzarella balls, pine nuts.', 'Toss cooked pasta with pesto, tomatoes, mozzarella, top with pine nuts.', 20, 4, NULL, 10, 25, 1.6, 100, 15, 3, 320, 14, 4, 310, 1, 0, 1, 0, 0, 0),
(51, 'Garlic Butter Shrimp', 'Juicy shrimp sauted in a rich garlic butter sauce.', 'Shrimp, garlic, butter, parsley, lemon juice, salt, pepper.', 'Saut shrimp in garlic butter, finish with parsley, lemon juice.', 15, 4, NULL, 24, 28, 1.4, 70, 0, 0, 220, 8, 0, 880, 0, 0, 0, 0, 0, 0),
(52, 'Chicken Tikka Masala', 'Rich and creamy chicken tikka masala with a blend of spices.', 'Chicken, yogurt, tikka masala paste, tomatoes, cream, onions, garlic.', 'Marinate chicken in yogurt and spices, grill, simmer in masala sauce.', 60, 6, NULL, 25, 30, 2.6, 80, 10, 3, 460, 18, 5, 720, 0, 0, 0, 0, 0, 0),
(53, 'Beet and Goat Cheese Salad', 'A colorful salad with roasted beets, goat cheese, walnuts, and arugula.', 'Beets, goat cheese, walnuts, arugula, vinaigrette.', 'Roast beets, assemble salad with cheese, walnuts, arugula, dress.', 45, 4, NULL, 6, 24, 1.8, 50, 20, 5, 230, 12, 7, 560, 1, 0, 1, 0, 0, 0),
(54, 'Portobello Mushroom Burgers', 'Grilled portobello mushrooms served as burgers with all the fixings.', 'Portobello mushrooms, whole wheat buns, lettuce, tomato, avocado, mayo.', 'Grill mushrooms, serve on buns with lettuce, tomato, avocado.', 25, 4, NULL, 8, 32, 2, 30, 8, 6, 320, 14, 5, 400, 1, 0, 1, 0, 0, 0),
(55, 'Red Velvet Cupcakes', 'Moist red velvet cupcakes topped with creamy cream cheese frosting.', 'Flour, cocoa powder, buttermilk, sugar, butter, cream cheese, red food coloring.', 'Bake cupcakes, frost with cream cheese frosting.', 45, 12, NULL, 3, 15, 0.9, 60, 0, 1, 260, 12, 20, 150, 0, 0, 1, 0, 0, 0),
(56, 'Asparagus Frittata', 'An easy and delicious asparagus frittata, perfect for brunch.', 'Eggs, asparagus, onion, parmesan cheese, olive oil, salt, pepper.', 'Saut asparagus and onion, add beaten eggs, cook until set, top with parmesan.', 30, 4, NULL, 12, 40, 2.1, 110, 15, 2, 200, 14, 3, 320, 1, 0, 1, 0, 0, 1),
(57, 'Hummus', 'Creamy homemade hummus made with chickpeas, tahini, lemon, and garlic.', 'Chickpeas, tahini, lemon juice, garlic, olive oil, salt.', 'Blend all ingredients until smooth, serve with olive oil drizzle.', 10, 6, NULL, 6, 60, 2.5, 80, 0, 7, 270, 14, 2, 150, 1, 1, 1, 1, 0, 0),
(58, 'Pineapple Fried Rice', 'A sweet and savory fried rice with pineapple, cashews, and shrimp.', 'Rice, pineapple, shrimp, cashews, peas, carrots, soy sauce.', 'Saut shrimp, add rice, pineapple, veggies, cashews, soy sauce.', 30, 4, NULL, 15, 35, 2.3, 45, 20, 2, 360, 5, 12, 780, 0, 0, 1, 0, 0, 0),
(59, 'Spinach Artichoke Dip', 'A creamy and cheesy spinach artichoke dip, perfect for parties.', 'Spinach, artichoke hearts, cream cheese, sour cream, parmesan, garlic.', 'Mix ingredients, bake until bubbly and golden.', 30, 8, NULL, 7, 25, 1.3, 150, 10, 2, 220, 18, 3, 580, 1, 0, 1, 0, 0, 0),
(60, 'Maple Glazed Salmon', 'Salmon fillets glazed with a sweet and tangy maple syrup sauce.', 'Salmon, maple syrup, soy sauce, garlic, ginger, olive oil.', 'Glaze salmon with mixture, bake until caramelized.', 20, 4, NULL, 23, 30, 1.6, 70, 0, 0, 300, 13, 8, 610, 0, 0, 1, 0, 0, 0),
(61, 'Raspberry Almond Thumbprint Cookies', 'Buttery almond cookies filled with raspberry jam.', 'Butter, sugar, almond extract, flour, raspberry jam.', 'Make cookies, indent, fill with jam, bake until golden.', 30, 24, NULL, 2, 10, 0.5, 20, 0, 1, 110, 5, 7, 45, 0, 0, 1, 0, 0, 0),
(62, 'Watermelon Feta Salad', 'A refreshing salad with juicy watermelon, feta cheese, and mint.', 'Watermelon, feta cheese, mint, balsamic glaze.', 'Combine watermelon, feta, mint, drizzle with balsamic glaze.', 10, 4, NULL, 5, 15, 0.7, 80, 19, 1, 120, 7, 9, 250, 1, 0, 1, 0, 0, 0),
(63, 'Roasted Chickpea Gyros', 'A vegetarian gyro with crispy roasted chickpeas and a creamy tzatziki sauce.', 'Chickpeas, tzatziki sauce, tomatoes, cucumbers, whole wheat pitas, spices.', 'Roast spiced chickpeas, serve in pitas with tzatziki, tomatoes, and cucumbers.', 40, 4, NULL, 12, 45, 3, 50, 20, 7, 320, 9, 5, 420, 1, 1, 1, 0, 0, 0),
(64, 'Cauliflower Buffalo Wings', 'Spicy and tangy cauliflower bites, served with blue cheese dressing.', 'Cauliflower, buffalo sauce, butter, garlic powder, flour, milk.', 'Batter and bake cauliflower, toss in buffalo sauce, serve with dressing.', 30, 4, NULL, 5, 20, 1.2, 25, 40, 3, 150, 8, 2, 610, 1, 0, 0, 0, 0, 0),
(65, 'Avocado Cilantro Lime Rice', 'Fluffy rice with avocado, lime, and cilantro for a fresh side dish.', 'Rice, avocado, lime juice, cilantro, garlic, salt.', 'Mix cooked rice with avocado, lime juice, cilantro, and garlic.', 25, 6, NULL, 4, 30, 1.1, 20, 10, 2, 210, 7, 1, 5, 1, 1, 1, 1, 1, 0),
(66, 'Sweet and Sour Tofu', 'Crispy tofu tossed in a homemade sweet and sour sauce with pineapple and bell peppers.', 'Tofu, pineapple, bell peppers, vinegar, sugar, soy sauce, cornstarch.', 'Fry tofu, mix with pineapple, peppers, and sauce, simmer until thickened.', 30, 4, NULL, 12, 25, 2, 30, 60, 3, 310, 10, 14, 460, 1, 1, 1, 0, 1, 0),
(67, 'Quiche Lorraine', 'A classic French quiche with bacon, cheese, and a creamy egg custard.', 'Bacon, swiss cheese, eggs, cream, pie crust, nutmeg.', 'Fill pie crust with bacon and cheese, pour over egg mixture, bake until set.', 45, 6, NULL, 14, 22, 2.2, 210, 0, 0, 410, 25, 2, 720, 0, 0, 0, 0, 0, 0),
(68, 'Miso Soup', 'A soothing Japanese soup with miso, seaweed, tofu, and green onions.', 'Miso paste, tofu, seaweed, green onions, dashi broth.', 'Dissolve miso in dashi broth, add tofu and seaweed, garnish with green onions.', 20, 4, NULL, 7, 28, 1.5, 60, 15, 2, 70, 3, 2, 800, 1, 1, 1, 1, 0, 0),
(69, 'Balsamic Bruschetta', 'A fresh tomato and basil topping on toasted bread, drizzled with balsamic glaze.', 'Tomatoes, basil, garlic, balsamic vinegar, olive oil, baguette.', 'Mix tomatoes, basil, garlic, vinegar, oil, spoon onto toasted bread slices.', 15, 6, NULL, 6, 20, 1.3, 30, 20, 2, 180, 5, 3, 210, 1, 1, 1, 0, 0, 0),
(70, 'Fish Tacos', 'Grilled fish tacos with cabbage slaw and a creamy lime sauce.', 'White fish, cabbage, lime, sour cream, corn tortillas, spices.', 'Grill spiced fish, mix cabbage with lime and cream, serve in tortillas.', 20, 4, NULL, 23, 30, 2.4, 70, 20, 3, 290, 9, 2, 310, 0, 0, 1, 0, 0, 0),
(71, 'Mango Chutney Chicken', 'Baked chicken breasts topped with a sweet and spicy mango chutney.', 'Chicken breasts, mango chutney, garlic, ginger, red pepper flakes.', 'Bake chicken with garlic, ginger, top with chutney and bake until done.', 35, 4, NULL, 26, 27, 2.5, 30, 10, 0, 320, 5, 12, 350, 0, 0, 1, 0, 0, 0),
(72, 'Vegetarian Chili', 'A hearty chili made with beans, tomatoes, and a blend of spices.', 'Kidney beans, black beans, tomatoes, corn, chili powder, onion, garlic.', 'Cook all ingredients until thickened, serve with avocado and sour cream.', 45, 6, NULL, 13, 40, 3.6, 80, 30, 8, 260, 7, 6, 460, 1, 1, 1, 1, 0, 0),
(73, 'Saffron Risotto', 'A rich and creamy risotto infused with saffron threads.', 'Arborio rice, chicken broth, saffron, parmesan cheese, onion, white wine.', 'Cook rice with saffron-infused broth, stir in parmesan.', 50, 4, NULL, 9, 23, 1.8, 100, 0, 1, 350, 8, 1, 550, 0, 0, 1, 0, 0, 0),
(74, 'Lemon Herb Roasted Chicken', 'A juicy roasted chicken seasoned with lemon and herbs.', 'Whole chicken, lemon, rosemary, thyme, garlic, butter.', 'Roast chicken with lemon, herbs, and garlic butter until golden.', 90, 6, NULL, 27, 32, 2.7, 70, 25, 0, 390, 22, 0, 640, 0, 0, 0, 0, 0, 0),
(75, 'Pumpkin Spice Smoothie', 'A creamy smoothie with pumpkin, banana, and a hint of spice.', 'Pumpkin puree, banana, almond milk, pumpkin spice, maple syrup.', 'Blend all ingredients until smooth, garnish with a sprinkle of spice.', 10, 2, NULL, 4, 24, 1.4, 50, 12, 3, 150, 2, 10, 55, 1, 1, 1, 1, 0, 1),
(76, 'Lentil and Sweet Potato Stew', 'A comforting stew with lentils, sweet potatoes, and warm spices.', 'Lentils, sweet potatoes, carrots, onion, garlic, cumin, vegetable broth.', 'Simmer all ingredients until lentils and potatoes are tender.', 55, 6, NULL, 18, 45, 3.3, 80, 22, 9, 310, 2, 7, 420, 1, 1, 1, 1, 0, 0),
(77, 'Greek Yogurt Parfait', 'A layered parfait with Greek yogurt, granola, and mixed berries.', 'Greek yogurt, granola, mixed berries, honey.', 'Layer yogurt, granola, and berries in glasses, drizzle with honey.', 10, 2, NULL, 12, 20, 0.8, 150, 10, 4, 220, 6, 15, 85, 1, 0, 1, 1, 0, 1),
(78, 'Butter Chicken', 'A popular Indian curry dish with tender chicken in a creamy tomato sauce.', 'Chicken, tomatoes, cream, butter, garam masala, garlic, ginger.', 'Cook chicken, simmer in sauce with spices until creamy.', 60, 4, NULL, 25, 35, 2.9, 70, 15, 3, 470, 27, 4, 710, 0, 0, 0, 0, 0, 0),
(79, 'Zesty Lime Shrimp Avocado Salad', 'A refreshing salad with shrimp, avocado, and a lime dressing.', 'Shrimp, avocado, lime, red onion, cilantro, olive oil.', 'Mix shrimp with avocado, onion, cilantro, dress with lime and oil.', 20, 4, NULL, 20, 35, 2.1, 60, 25, 5, 300, 15, 3, 400, 0, 0, 1, 0, 0, 0),
(80, 'Black Bean Soup', 'A savory and spicy soup made with black beans and vegetables.', 'Black beans, vegetable broth, onion, garlic, cumin, chili powder.', 'Cook all ingredients until thick, blend until smooth.', 35, 6, NULL, 14, 55, 3.7, 70, 20, 8, 240, 1, 2, 480, 1, 1, 1, 1, 0, 0),
(81, 'Chocolate Hazelnut Spread', 'Homemade chocolate hazelnut spread, perfect for toast and desserts.', 'Hazelnuts, cocoa powder, powdered sugar, vanilla extract, oil.', 'Blend hazelnuts until smooth, add remaining ingredients, blend until creamy.', 15, 10, NULL, 4, 50, 2.5, 60, 0, 3, 210, 15, 22, 10, 1, 0, 1, 0, 0, 0),
(82, 'Spaghetti Aglio e Olio', 'A simple Italian pasta dish with garlic, olive oil, and chili flakes.', 'Spaghetti, garlic, olive oil, chili flakes, parsley.', 'Cook spaghetti, saut garlic in oil, mix with pasta, garnish with parsley.', 20, 4, NULL, 7, 25, 1.3, 20, 0, 2, 320, 14, 1, 10, 0, 0, 1, 0, 1, 0),
(83, 'Kimchi Fried Rice', 'Spicy and tangy fried rice made with kimchi and topped with a fried egg.', 'Rice, kimchi, onion, garlic, soy sauce, sesame oil, eggs.', 'Saut onion and garlic, add kimchi and rice, fry and top with a fried egg.', 25, 4, NULL, 8, 22, 1.8, 50, 18, 2, 320, 10, 6, 720, 0, 0, 0, 0, 0, 0),
(84, 'Broccoli Almond Soup', 'Creamy broccoli soup enriched with ground almonds and spices.', 'Broccoli, almonds, onion, vegetable broth, cream, spices.', 'Cook broccoli and onion, blend with almonds and broth, simmer with cream and spices.', 35, 4, NULL, 5, 40, 1.5, 80, 15, 4, 220, 15, 3, 300, 1, 0, 1, 0, 0, 0),
(85, 'Egg Salad Sandwich', 'A classic egg salad sandwich with creamy mayonnaise and crisp lettuce.', 'Eggs, mayonnaise, mustard, lettuce, whole wheat bread, salt, pepper.', 'Mix chopped eggs with mayonnaise and mustard, season, serve on bread with lettuce.', 20, 2, NULL, 12, 20, 1.2, 100, 5, 2, 340, 18, 2, 450, 0, 0, 1, 1, 0, 1),
(86, 'Roasted Garlic Hummus', 'Homemade hummus with the rich flavor of roasted garlic.', 'Chickpeas, tahini, roasted garlic, lemon juice, olive oil.', 'Blend all ingredients until smooth, garnish with olive oil and paprika.', 10, 8, NULL, 6, 30, 2, 60, 0, 6, 270, 14, 1, 210, 1, 1, 1, 1, 0, 0),
(87, 'Caramelized Onion Tart', 'Savory tart with sweet caramelized onions and melted cheese on a flaky crust.', 'Pie crust, onions, cheese, thyme, butter, salt.', 'Caramelize onions, fill pie crust, top with cheese and bake.', 60, 6, NULL, 7, 25, 1.7, 150, 12, 2, 410, 22, 5, 520, 0, 0, 1, 0, 0, 0),
(88, 'Beef Stroganoff', 'Tender beef strips in a creamy mushroom sauce, served over egg noodles.', 'Beef strips, mushrooms, onions, sour cream, beef broth, egg noodles.', 'Saut beef, add mushrooms and onions, stir in broth and sour cream, serve over noodles.', 45, 4, NULL, 25, 50, 3.2, 100, 5, 3, 600, 30, 7, 850, 0, 0, 0, 0, 0, 0),
(89, 'Vegetable Spring Rolls', 'Crispy spring rolls filled with fresh vegetables and served with a dipping sauce.', 'Cabbage, carrots, bell peppers, spring roll wrappers, soy sauce, ginger.', 'Fill wrappers with vegetables, fry until golden, serve with sauce.', 30, 8, NULL, 4, 20, 1, 25, 19, 2, 150, 5, 2, 300, 1, 0, 1, 0, 0, 0),
(90, 'Cinnamon Apple Chips', 'Crispy and sweet apple chips sprinkled with cinnamon sugar.', 'Apples, cinnamon, sugar.', 'Thinly slice apples, sprinkle with cinnamon sugar, bake until crisp.', 120, 4, NULL, 0, 10, 0.5, 20, 0, 4, 90, 0, 12, 5, 1, 0, 1, 1, 0, 1),
(91, 'Jambalaya', 'A spicy Creole rice dish with chicken, sausage, and shrimp.', 'Chicken, sausage, shrimp, rice, tomatoes, onions, peppers, Creole seasoning.', 'Cook meats, add vegetables and rice, simmer with seasoning.', 60, 6, NULL, 23, 40, 3, 90, 25, 2, 450, 15, 5, 900, 0, 0, 0, 0, 0, 0),
(92, 'Zucchini Bread', 'Moist and flavorful bread made with fresh zucchini.', 'Zucchini, flour, sugar, eggs, vanilla, cinnamon, baking powder.', 'Mix ingredients, pour into loaf pan, bake until a toothpick comes out clean.', 55, 8, NULL, 6, 30, 1.5, 80, 10, 3, 260, 12, 18, 280, 0, 0, 1, 0, 0, 1),
(93, 'Pesto Grilled Cheese', 'A gooey grilled cheese sandwich with homemade pesto.', 'Bread, cheese, pesto, butter.', 'Spread pesto on bread, add cheese, butter outer slices, grill until golden.', 15, 2, NULL, 12, 20, 1.8, 200, 0, 2, 400, 22, 2, 670, 0, 0, 0, 0, 0, 1),
(94, 'Tomato Galette', 'Rustic galette with ripe tomatoes, cheese, and herbs on a buttery crust.', 'Pie dough, tomatoes, cheese, basil, olive oil, garlic.', 'Layer dough with cheese, tomatoes, season, bake until crust is golden.', 70, 6, NULL, 9, 28, 2.1, 150, 15, 3, 350, 18, 4, 320, 1, 0, 1, 0, 0, 0),
(95, 'Sesame Noodle Salad', 'Cold noodle salad with a tangy sesame dressing and crisp vegetables.', 'Noodles, sesame oil, soy sauce, vinegar, sugar, carrots, cucumbers.', 'Mix noodles with dressing, add sliced vegetables.', 20, 4, NULL, 7, 35, 2.2, 30, 15, 3, 320, 10, 8, 400, 1, 1, 1, 1, 0, 0),
(96, 'Baked Oatmeal Cups', 'Portable oatmeal cups with your choice of fruits and nuts.', 'Oats, milk, eggs, baking powder, vanilla, fruit, nuts.', 'Combine ingredients, pour into muffin tins, bake.', 30, 12, NULL, 5, 25, 1.6, 50, 0, 4, 150, 7, 5, 100, 0, 0, 1, 1, 0, 1),
(97, 'Creamy Avocado Pasta', 'Pasta in a rich and creamy avocado sauce, ready in minutes.', 'Pasta, ripe avocados, garlic, lemon, olive oil, parmesan.', 'Blend sauce ingredients, mix with cooked pasta.', 20, 4, NULL, 8, 32, 1.9, 50, 20, 5, 360, 18, 3, 20, 1, 0, 1, 0, 0, 0),
(98, 'Raspberry Lemon Bars', 'Tart lemon bars with a raspberry twist and a buttery crust.', 'Flour, butter, sugar, lemon juice, eggs, raspberries.', 'Prepare crust, mix filling, bake until set.', 45, 8, NULL, 4, 15, 0.7, 30, 25, 1, 220, 9, 14, 180, 0, 0, 1, 0, 0, 0),
(99, 'Shrimp Scampi', 'Shrimp cooked in a buttery garlic lemon sauce, served over pasta or rice.', 'Shrimp, garlic, butter, lemon, parsley, pasta or rice.', 'Saut shrimp in garlic and butter, add lemon, serve over pasta or rice.', 25, 4, NULL, 22, 31, 2.3, 100, 20, 0, 350, 14, 1, 650, 0, 0, 0, 0, 0, 0),
(100, 'Corn Chowder', 'A creamy corn chowder with potatoes and bacon for a comforting meal.', 'Corn, potatoes, onion, bacon, milk, chicken broth, spices.', 'Cook bacon, saut vegetables, add broth and milk, simmer until thick.', 60, 6, NULL, 10, 45, 2.8, 90, 12, 5, 310, 12, 6, 780, 0, 0, 0, 0, 0, 0),
(101, 'Blueberry Cheesecake', 'Creamy cheesecake with a tangy blueberry topping and a graham cracker crust.', 'Cream cheese, sugar, eggs, blueberries, lemon, graham crackers.', 'Mix filling, pour into crust, bake, top with blueberry sauce.', 90, 8, NULL, 6, 18, 1.3, 80, 0, 2, 420, 25, 22, 310, 0, 0, 1, 0, 0, 0),
(102, 'Roasted Brussels Sprouts', 'Brussels sprouts roasted with olive oil and seasonings until crisp.', 'Brussels sprouts, olive oil, salt, pepper, garlic powder.', 'Toss sprouts with oil and seasonings, roast until caramelized.', 40, 4, NULL, 5, 30, 2, 56, 69, 4, 120, 7, 2, 200, 1, 1, 1, 1, 0, 0),
(103, 'Chia Breakfast Bowl', 'A nutritious bowl of chia seeds soaked overnight in almond milk, topped with fresh fruits and nuts.', 'Chia seeds, almond milk, honey, mixed berries, sliced almonds, banana.', 'Soak chia seeds in almond milk overnight, top with honey, berries, almonds, and banana slices in the morning.', 480, 2, NULL, 6, 50, 2.5, 100, 30, 10, 250, 8, 12, 30, 1, 1, 1, 1, 1, 1),
(104, 'Protein-Packed Pancakes', 'Whole grain pancakes packed with protein powder, perfect for a post-workout meal.', 'Whole wheat flour, protein powder, milk, egg, banana, baking powder.', 'Mix ingredients, cook on a non-stick pan until bubbles form, flip to cook the other side.', 15, 3, NULL, 20, 45, 2.7, 200, 0, 5, 350, 10, 7, 200, 0, 0, 1, 0, 1, 1),
(105, 'Overnight Oats with Peanut Butter', 'Creamy overnight oats with the richness of peanut butter and the sweetness of honey.', 'Rolled oats, almond milk, peanut butter, honey, chia seeds.', 'Mix all ingredients and let sit overnight. Serve cold.', 480, 2, NULL, 8, 55, 2.8, 150, 0, 7, 300, 14, 10, 120, 1, 0, 1, 1, 1, 1),
(106, 'Smoked Salmon Avocado Toast', 'Hearty whole grain toast topped with creamy avocado and rich smoked salmon.', 'Whole grain bread, smoked salmon, avocado, lemon juice, dill.', 'Mash avocado with lemon juice, spread on toast, top with salmon and dill.', 10, 2, NULL, 15, 35, 2.2, 50, 15, 5, 320, 20, 3, 580, 0, 0, 1, 1, 1, 1),
(107, 'Greek Yogurt Smoothie', 'A refreshing smoothie made with Greek yogurt, bananas, and mixed berries.', 'Greek yogurt, banana, mixed berries, honey, milk.', 'Blend all ingredients until smooth.', 5, 2, NULL, 10, 18, 1.5, 150, 20, 3, 200, 2, 15, 80, 1, 0, 1, 1, 1, 1),
(108, 'Spinach and Mushroom Omelette', 'A fluffy omelette filled with sauted mushrooms and spinach.', 'Eggs, spinach, mushrooms, olive oil, cheese.', 'Saut vegetables, whisk eggs and pour over, cook, fold in cheese.', 20, 2, NULL, 12, 40, 3, 200, 0, 2, 250, 18, 2, 400, 0, 0, 1, 0, 0, 1),
(109, 'Whole Grain Waffles', 'Crispy on the outside, fluffy on the inside whole grain waffles.', 'Whole wheat flour, milk, eggs, vegetable oil, baking powder, sugar.', 'Mix ingredients, pour into waffle iron, cook until golden.', 20, 4, NULL, 8, 30, 2.1, 100, 0, 4, 220, 9, 8, 210, 0, 0, 1, 0, 1, 1),
(110, 'Fruit and Nut Parfait', 'A layered parfait with yogurt, granola, fresh fruits, and nuts.', 'Greek yogurt, granola, mixed fresh fruits, almonds, honey.', 'Layer yogurt, granola, fruits, and nuts in glasses, drizzle with honey.', 10, 2, NULL, 10, 25, 1.6, 120, 50, 4, 280, 8, 12, 55, 1, 0, 1, 1, 0, 1),
(111, 'Avocado and Egg Breakfast Pizza', 'A delicious breakfast pizza with avocado spread, topped with eggs and bacon.', 'Pizza dough, eggs, avocado, bacon, cheese.', 'Spread avocado on dough, top with bacon and eggs, bake until egg is set.', 30, 4, NULL, 20, 40, 3.3, 220, 15, 5, 450, 22, 4, 720, 0, 0, 1, 0, 1, 1),
(112, 'Berry and Chia Yogurt Bowl', 'A vibrant yogurt bowl with chia seeds, mixed berries, and a touch of honey.', 'Greek yogurt, chia seeds, mixed berries, honey.', 'Mix yogurt and chia seeds, top with berries and a drizzle of honey.', 10, 2, NULL, 12, 30, 2.4, 100, 40, 6, 280, 10, 11, 85, 1, 0, 1, 1, 0, 1),
(113, 'Sweet Corn Fritters', 'Crispy fritters made with sweet corn and spices, served with a creamy yogurt dip.', 'Sweet corn, flour, eggs, spices, yogurt.', 'Mix corn, flour, eggs, and spices, fry until golden, serve with yogurt dip.', 30, 4, NULL, 6, 20, 1.5, 80, 0, 2, 210, 10, 3, 250, 0, 0, 0, 1, 0, 0),
(114, 'Cucumber Tomato Salad', 'A refreshing salad with cucumbers, tomatoes, onion, and a vinegar dressing.', 'Cucumbers, tomatoes, red onion, olive oil, vinegar.', 'Combine vegetables, dress with oil and vinegar.', 15, 4, NULL, 2, 15, 1, 30, 20, 2, 120, 5, 4, 10, 1, 1, 1, 1, 1, 0),
(115, 'Creamy Mushroom Toast', 'Savory sauted mushrooms on creamy spread toast.', 'Mushrooms, cream cheese, garlic, parsley, whole grain bread.', 'Saut mushrooms with garlic, spread cream cheese on toast, top with mushrooms.', 15, 2, NULL, 8, 22, 1.7, 60, 8, 3, 310, 15, 2, 410, 0, 0, 1, 1, 0, 1),
(116, 'Quiche with Spinach and Feta', 'A delicious quiche with a filling of spinach, feta, and eggs in a flaky crust.', 'Pie crust, spinach, feta cheese, eggs, cream.', 'Mix spinach, feta, eggs, and cream, pour into crust, bake.', 60, 6, NULL, 14, 35, 2.2, 150, 0, 2, 320, 22, 3, 470, 0, 0, 1, 0, 0, 1),
(117, 'Almond Butter Smoothie', 'A smooth and creamy smoothie made with almond butter, banana, and almond milk.', 'Almond butter, banana, almond milk, honey.', 'Blend all ingredients until smooth.', 5, 2, NULL, 8, 30, 1.9, 50, 0, 4, 280, 16, 12, 40, 1, 1, 1, 1, 1, 1),
(118, 'Breakfast Quinoa Bowl', 'A hearty breakfast bowl with quinoa, almond milk, cinnamon, and apples.', 'Quinoa, almond milk, cinnamon, apple, nuts.', 'Cook quinoa in almond milk with cinnamon, top with apple slices and nuts.', 20, 2, NULL, 7, 55, 2.6, 80, 5, 5, 300, 8, 7, 115, 1, 1, 1, 1, 1, 1),
(119, 'Scrambled Eggs with Spinach', 'Fluffy scrambled eggs with fresh spinach and a touch of garlic.', 'Eggs, spinach, garlic, olive oil, salt, pepper.', 'Saut spinach with garlic, scramble eggs in mixture.', 10, 2, NULL, 12, 30, 2.1, 100, 0, 3, 200, 14, 1, 310, 0, 0, 1, 0, 0, 1),
(120, 'Berry Breakfast Muffins', 'Whole grain muffins loaded with fresh berries.', 'Whole wheat flour, mixed berries, eggs, milk, sugar.', 'Mix ingredients, pour into muffin tins, bake until golden.', 25, 12, NULL, 5, 20, 1.4, 50, 0, 3, 180, 6, 10, 200, 0, 0, 1, 1, 0, 1),
(121, 'Granola Yogurt Popsicles', 'Frozen yogurt popsicles with granola and mixed berries, perfect for a hot day.', 'Greek yogurt, honey, mixed berries, granola.', 'Layer yogurt mixed with honey, berries, and granola in popsicle molds, freeze.', 480, 6, NULL, 6, 18, 1.6, 120, 20, 2, 100, 2, 8, 30, 1, 0, 1, 1, 0, 1),
(122, 'Savory Breakfast Skillet', 'A hearty skillet with potatoes, eggs, and vegetables, topped with cheese.', 'Potatoes, eggs, bell peppers, onions, cheese, olive oil.', 'Saut potatoes and vegetables, crack eggs into skillet, top with cheese, cover until eggs are set.', 30, 4, NULL, 12, 40, 2.3, 150, 25, 4, 350, 18, 3, 420, 0, 0, 1, 0, 0, 1),
(123, 'Roasted Turkey with Herb Butter', 'Juicy roasted turkey covered in a savory herb butter.', 'Turkey, butter, rosemary, thyme, garlic, lemon.', 'Rub turkey with herb butter, roast until golden and cooked through.', 240, 8, NULL, 70, 35, 3.8, 90, 25, 0, 590, 22, 2, 650, 0, 0, 0, 0, 0, 0),
(124, 'Beef Bourguignon', 'Rich French stew made with beef, red wine, mushrooms, and bacon.', 'Beef chuck, red wine, mushrooms, bacon, onions, carrots, garlic.', 'Brown beef, saut vegetables, simmer with wine and beef stock until tender.', 180, 6, NULL, 40, 50, 4.2, 70, 20, 5, 450, 18, 6, 700, 0, 0, 0, 0, 0, 0),
(125, 'Vegetarian Moussaka', 'Layered eggplant and potato casserole with a creamy bchamel sauce.', 'Eggplant, potatoes, lentils, tomatoes, bchamel sauce, cheese.', 'Layer roasted eggplant and potatoes with lentils and tomato sauce, top with bchamel, bake.', 90, 6, NULL, 15, 45, 3.1, 220, 35, 7, 400, 20, 8, 550, 1, 0, 1, 0, 0, 0),
(126, 'Lamb Tagine', 'Slow-cooked Moroccan lamb stew with dried fruits and spices.', 'Lamb shoulder, prunes, apricots, cinnamon, cumin, ginger, almonds.', 'Cook lamb with spices and fruits, simmer until tender, serve with almonds.', 120, 4, NULL, 44, 55, 4.5, 100, 30, 6, 520, 25, 9, 400, 0, 0, 0, 0, 0, 0),
(127, 'Seafood Paella', 'Spanish rice dish with a variety of seafood, cooked in a saffron-infused broth.', 'Rice, shrimp, mussels, clams, chicken, saffron, peas, tomatoes.', 'Cook rice with saffron broth, add seafood and chicken, cook until done.', 90, 6, NULL, 30, 60, 4.8, 80, 40, 4, 600, 22, 5, 750, 0, 0, 0, 0, 0, 0),
(128, 'Stuffed Acorn Squash', 'Roasted acorn squash filled with a savory mix of quinoa, cranberries, and nuts.', 'Acorn squash, quinoa, cranberries, walnuts, spinach, goat cheese.', 'Roast squash, mix quinoa with cranberries, nuts, and spinach, stuff squash, bake.', 60, 4, NULL, 8, 30, 2.3, 90, 25, 5, 350, 15, 7, 300, 1, 0, 1, 0, 0, 0),
(129, 'Ratatouille on Polenta', 'Classic ratatouille served on creamy polenta.', 'Eggplant, zucchini, bell pepper, tomato, onion, garlic, cornmeal, cheese.', 'Make ratatouille, cook polenta with cheese, serve ratatouille on polenta.', 70, 4, NULL, 9, 40, 2.7, 80, 30, 6, 310, 14, 8, 480, 1, 0, 1, 0, 0, 0),
(130, 'Thai Basil Chicken', 'Spicy Thai dish with chicken, basil, and chilli, served over jasmine rice.', 'Chicken, Thai basil, chilli, soy sauce, garlic, jasmine rice.', 'Stir-fry chicken with basil and chilli, serve over rice.', 30, 4, NULL, 26, 40, 3.4, 60, 25, 3, 500, 12, 4, 720, 0, 0, 1, 0, 0, 0),
(131, 'Balsamic Roasted Vegetables', 'Vegetables roasted with balsamic vinegar and herbs.', 'Carrots, zucchini, bell peppers, balsamic vinegar, olive oil, thyme.', 'Toss vegetables with vinegar and oil, roast until caramelized.', 45, 4, NULL, 4, 20, 1.9, 55, 45, 6, 200, 9, 5, 250, 1, 1, 1, 1, 0, 0),
(132, 'Pulled Pork Sandwich', 'Slow-cooked pork shoulder, shredded and served on a bun with BBQ sauce.', 'Pork shoulder, BBQ sauce, onion, garlic, buns.', 'Slow cook pork with BBQ sauce, shred, serve on buns.', 480, 8, NULL, 35, 60, 4.6, 70, 20, 0, 550, 25, 20, 950, 0, 0, 0, 0, 0, 0),
(133, 'Vegetarian Kofta Curry', 'Spiced vegetarian meatballs in a creamy tomato curry sauce.', 'Chickpeas, potatoes, peas, garam masala, tomatoes, cream.', 'Form koftas from mixture, fry, simmer in curry sauce.', 60, 4, NULL, 12, 50, 3.9, 90, 15, 8, 450, 22, 7, 400, 1, 0, 1, 0, 0, 0),
(134, 'Gnocchi with Tomato Sauce', 'Soft gnocchi tossed in a rich tomato basil sauce.', 'Gnocchi, tomatoes, basil, garlic, olive oil, parmesan.', 'Cook gnocchi, simmer with tomato sauce, serve with parmesan.', 30, 4, NULL, 10, 25, 2.1, 120, 15, 4, 350, 16, 6, 410, 1, 0, 1, 0, 0, 0),
(135, 'Mushroom Stroganoff', 'A creamy and savory mushroom version of the classic stroganoff.', 'Mushrooms, sour cream, onion, garlic, paprika, egg noodles.', 'Saut mushrooms, onion, garlic, add sour cream and paprika, serve over noodles.', 35, 4, NULL, 14, 45, 3.2, 110, 10, 6, 420, 20, 5, 480, 1, 0, 1, 0, 0, 0),
(136, 'Lemon Garlic Roasted Chicken', 'Roasted chicken with a crisp skin, flavored with lemon and garlic.', 'Chicken, lemon, garlic, butter, rosemary.', 'Rub chicken with garlic butter, roast with lemon and rosemary.', 120, 6, NULL, 50, 55, 4.7, 90, 20, 0, 630, 30, 3, 690, 0, 0, 0, 0, 0, 0),
(137, 'Shepherd\'s Pie', 'A comforting pie with a ground meat layer, topped with mashed potatoes.', 'Ground beef or lamb, potatoes, carrots, peas, onion, gravy.', 'Layer cooked meat and vegetables with gravy, top with mashed potatoes, bake.', 90, 6, NULL, 22, 50, 3.6, 100, 15, 5, 540, 28, 6, 760, 0, 0, 0, 0, 0, 0),
(138, 'Roasted Duck with Orange Sauce', 'Crispy roasted duck served with a tangy orange sauce.', 'Duck, orange juice, sugar, vinegar, stock.', 'Roast duck, deglaze pan with orange sauce ingredients, serve over duck.', 150, 4, NULL, 55, 70, 5.1, 110, 20, 0, 690, 40, 8, 620, 0, 0, 0, 0, 0, 0),
(139, 'Cajun Shrimp and Rice', 'Spicy Cajun-seasoned shrimp cooked with rice and vegetables.', 'Shrimp, rice, bell peppers, onion, Cajun seasoning, tomatoes.', 'Cook rice with vegetables and spices, add shrimp, cook until done.', 45, 4, NULL, 28, 55, 4.3, 80, 25, 4, 520, 15, 6, 800, 0, 0, 1, 0, 0, 0),
(140, 'Vegetable Curry', 'A rich and aromatic curry made with mixed vegetables and coconut milk.', 'Mixed vegetables, coconut milk, curry powder, onion, garlic, ginger.', 'Saut vegetables with spices, simmer in coconut milk.', 30, 4, NULL, 6, 35, 2.5, 60, 40, 7, 300, 14, 6, 440, 1, 1, 1, 1, 0, 0),
(141, 'Soy Glazed Salmon', 'Salmon fillets glazed with a sweet and savory soy sauce mixture.', 'Salmon, soy sauce, honey, ginger, garlic.', 'Glaze salmon with soy mixture, bake until cooked through.', 30, 4, NULL, 24, 45, 3, 70, 0, 0, 400, 18, 10, 630, 0, 0, 1, 1, 0, 0),
(142, 'Baked Ziti with Ricotta', 'Pasta baked with a mixture of ricotta cheese, marinara sauce, and mozzarella.', 'Ziti pasta, ricotta cheese, marinara sauce, mozzarella, parmesan.', 'Layer cooked pasta with cheeses and sauce, bake until bubbly.', 60, 8, NULL, 20, 55, 4, 150, 25, 6, 580, 22, 8, 840, 0, 0, 0, 0, 0, 0),
(143, 'Artichoke and Spinach Dip', 'Creamy dip with artichokes, spinach, and various cheeses, baked until golden.', 'Artichoke hearts, spinach, cream cheese, sour cream, parmesan, mozzarella.', 'Mix ingredients, bake until bubbly and golden.', 30, 8, NULL, 12, 30, 2.2, 200, 15, 4, 320, 25, 3, 690, 1, 0, 1, 0, 0, 0),
(144, 'Creamy Polenta with Wild Mushrooms', 'Soft polenta served with a ragout of wild mushrooms.', 'Polenta, wild mushrooms, vegetable broth, cream, parmesan.', 'Cook polenta, saut mushrooms, serve mushrooms over polenta.', 35, 4, NULL, 9, 45, 3, 80, 25, 7, 400, 20, 4, 500, 1, 0, 1, 0, 0, 0),
(145, 'Pork Belly Bao Buns', 'Steamed bao buns filled with crispy pork belly and pickled vegetables.', 'Pork belly, bao buns, soy sauce, sugar, vinegar, cucumber, carrots.', 'Cook pork belly with soy and sugar, fill steamed buns with pork and pickled vegetables.', 120, 8, NULL, 28, 60, 4.9, 90, 10, 3, 620, 24, 9, 850, 0, 0, 0, 0, 0, 0);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `recipe`
--
ALTER TABLE `recipe`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `recipe`
--
ALTER TABLE `recipe`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=146;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
